### ISSUE TITLE
deployment problem

### ISSUE THREAD

**Issue by jhan2505** [w3f/polkadot-validator-setup#106]
when I try to deploy the secure validator project on google cloud, it shows me the following error after creating the instances ... any idea of this error?

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.

Outputs:

ip_address = [
  "34.74.221.199",
]

["34.74.221.199"]

["34.73.9.214"]

Done
Syncing application...
node:events:304
      throw er; // Unhandled 'error' event
      ^

Error: spawn ansible-playbook ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:269:19)
    at onErrorNT (node:internal/child_process:465:16)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:275:12)
    at onErrorNT (node:internal/child_process:465:16)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ansible-playbook',
  path: 'ansible-playbook',
  spawnargs: [
    'main.yml',
    '-f',
    '30',
    '-i',
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by brenzi** [comment]
same here: 
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:


ip_address = [
  "34.65.164.154",
]

["34.65.164.154"]

Done
Syncing application...
events.js:353
      throw er; // Unhandled 'error' event
      ^

Error: spawn ansible-playbook ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ansible-playbook',
  path: 'ansible-playbook',
  spawnargs: [
    'main.yml',
    '-f',
    '30',
    '-i',
    '/home/#####/.config/polkadot-secure-validator/build/integritee/ansible/inventory'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The auto-generated inventory linked in the path above looks like this:
```
[validator_0]
34.65.164.154

[validator_0:vars]
ansible_user=integritee
telemetryUrl=wss://my.private.telemetry.endpoint
loggingFilter='sync=trace,afg=trace,babe=debug'
nodeName=testnode


[validator:children]
validator_0


[all:vars]
project=integritee
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ConnectTimeout=25 -o ControlMaster=no -o UserKnownHostsFile=/dev/null'
polkadot_binary_url='https://github.com/paritytech/polkadot/releases/download/v0.8.29/polkadot'
polkadot_binary_checksum='sha256:0b27d0cb99ca60c08c78102a9d2f513d89dfec8dbd6fdeba8b952a420cdc9fd2'
chain='kusama'
polkadot_network_id='ksmcc3'
build_dir=/home/abrenzikofer/.config/polkadot-secure-validator/build/integritee/ansible
nginx_user='prometheus'
nginx_password='nginx_password'
node_exporter_enabled='true'
node_exporter_binary_url='https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz'
node_exporter_binary_checksum='sha256:3369b76cd2b0ba678b6d618deab320e565c3d93ccb5c2a0d5db51a53857768ae'
polkadot_restart_enabled='true'
polkadot_restart_minute='50'
polkadot_restart_hour='4,12,20'
polkadot_restart_day='*'
polkadot_restart_month='*'
polkadot_restart_weekday='*'
polkadot_additional_common_flags=''
polkadot_additional_validator_flags=''
polkadot_additional_public_flags=''
polkadot_db_snapshot_url=''
polkadot_db_snapshot_checksum=''
```

**Comment by brenzi** [comment]
well, in my case it appears that ansible wasn't installed :blush:
```
pip3 install ansible
```
solved the problem
